#!/usr/bin/env python3

import webview
import sys
import os

def main():
    if len(sys.argv) != 2:
        print("Provide a page, dumbass.")
        exit(1)

    webview.create_window('',os.path.abspath(sys.argv[1]))
    webview.start()

if __name__ == "__main__":
    main()

