source ~/.vundlerc

syntax on
set visualbell
colorscheme solarized
set background=dark
set cindent

set backspace=indent,eol,start
imap <C-BS> <C-W>

set listchars=tab:•-

map <C-n> :NERDTreeToggle<CR>

